/**
 * ProjectRegistry — the source of truth for project metadata.
 *
 * A plain shared class (NOT a Plugin), in the same shape as ChannelRegistry /
 * ExecutorRegistry / IdentityRegistry: constructed once at startup and handed
 * to whichever plugins + routes need to read project metadata. Consumers hold
 * a reference to this *registry object*, not to another plugin — which is the
 * registrar exemption the plugin contract explicitly allows. (#633 review.)
 *
 * Pulls the canonical project list from the `workstacean-projects` sidecar
 * (`GET /api/settings/global` → `settings.projects[]`). That endpoint is a
 * static file served by nginx, regenerated by `sync-project-registry.sh`
 * (cron) from the GitHub `protoagent-plugin` topic + an explicit base set.
 * No auth: the sidecar serves a public static artifact on the internal
 * network. `workspace/projects.yaml` no longer exists.
 *
 * Each served project carries `id, name, path` plus native `github` +
 * `defaultBranch`. For workstacean's routing + cache needs we additionally
 * derive:
 *
 *   - `slug`          — `name.toLowerCase().replace(/[^a-z0-9]+/g, "-")`
 *   - `github`        — from the served field, or `<path>/.git/config` origin
 *   - `defaultBranch` — from the served field, or the `.git` symref
 *
 * Startup contract: `refreshNow()` is awaited by the host (src/index.ts)
 * before consumers are constructed; `start()` then arms the 5-min refresh.
 */

import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { logger } from "../../lib/log.ts";
import type { ProjectDirectory, RegistryProject } from "../../lib/types/projects.ts";

const log = logger("project-registry");

const DEFAULT_REGISTRY_URL = "http://workstacean-projects:8080";
const DEFAULT_REFRESH_INTERVAL_MS = 5 * 60_000;

// The project shape + the surface the integration plugins consume live in
// lib/types/projects.ts (lib can't import src). Re-exported for src consumers
// that treat this module as the registry's home.
export type { RegistryProject };

/** A project as the sidecar serves it from `/api/settings/global`. `github` +
 *  `defaultBranch` are native fields — present for current entries, optional so
 *  we can still derive from `.git` as a fallback. */
interface RawRegistryProject {
  id: string;
  name: string;
  path: string;
  github?: { owner: string; repo: string };
  defaultBranch?: string;
}

export interface ProjectRegistryOptions {
  /** Registry sidecar base URL. Default: `http://workstacean-projects:8080`. */
  apiBase?: string;
  /** Refresh interval. Default: 5 min. */
  refreshIntervalMs?: number;
}

export class ProjectRegistry implements ProjectDirectory {
  private readonly apiBase: string;
  private readonly refreshIntervalMs: number;

  private projects: RegistryProject[] = [];
  private refreshTimer?: ReturnType<typeof setInterval>;
  private lastRefreshAt = 0;
  private lastError: string | undefined;

  constructor(opts: ProjectRegistryOptions = {}) {
    this.apiBase = opts.apiBase ?? process.env["PROJECT_REGISTRY_URL"] ?? DEFAULT_REGISTRY_URL;
    this.refreshIntervalMs = opts.refreshIntervalMs ?? DEFAULT_REFRESH_INTERVAL_MS;
  }

  /**
   * Arm the periodic background refresh. The first fetch is expected to have
   * already happened via `await registry.refreshNow()` before consumers read
   * the registry — `start()` only schedules subsequent refreshes.
   */
  start(): void {
    if (this.refreshTimer) return;
    this.refreshTimer = setInterval(() => void this._refresh(), this.refreshIntervalMs);
    log.info(
      `Started — apiBase=${this.apiBase}, ` +
        `refresh=${Math.round(this.refreshIntervalMs / 60_000)}min, ` +
        `${this.projects.length} project(s) loaded`,
    );
  }

  stop(): void {
    if (this.refreshTimer) clearInterval(this.refreshTimer);
    this.refreshTimer = undefined;
    this.projects = [];
  }

  /** Snapshot of currently-known projects. */
  getProjects(): readonly RegistryProject[] {
    return this.projects;
  }

  /** Lookup by derived slug. */
  getBySlug(slug: string): RegistryProject | undefined {
    return this.projects.find((p) => p.slug === slug);
  }

  /** Lookup by `owner/repo` string (case-insensitive — GitHub coords are). */
  getByGithub(ownerRepo: string): RegistryProject | undefined {
    const needle = ownerRepo.toLowerCase();
    return this.projects.find(
      (p) => p.github && `${p.github.owner}/${p.github.repo}`.toLowerCase() === needle,
    );
  }

  /** Lookup by absolute filesystem path. */
  getByPath(path: string): RegistryProject | undefined {
    return this.projects.find((p) => p.path === path);
  }

  /** All known `owner/repo` coordinates (for monitored-repo lists / allowlists). */
  getGithubCoords(): string[] {
    return this.projects
      .filter((p) => p.github)
      .map((p) => `${p.github!.owner}/${p.github!.repo}`);
  }

  /** Last refresh timestamp (0 if never). */
  getLastRefreshAt(): number {
    return this.lastRefreshAt;
  }

  /** Last refresh error, if any. Cleared on next successful refresh. */
  getLastError(): string | undefined {
    return this.lastError;
  }

  /**
   * Force a synchronous-style refresh — used by the host at startup to
   * populate the registry before consumers read it. Surfaces fetch errors
   * via `getLastError()`; never throws.
   */
  async refreshNow(): Promise<void> {
    await this._refresh();
  }

  private async _refresh(): Promise<void> {
    try {
      const raw = await this._fetchProjects();
      this.projects = dedupeBySlug(raw.map((p) => this._enrichProject(p)));
      this.lastRefreshAt = Date.now();
      this.lastError = undefined;
      log.info(
        `Refreshed: ${this.projects.length} project(s) — ` +
          this.projects.map((p) => p.slug).join(", "),
      );
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      this.lastError = msg;
      log.warn(
        `Refresh failed (${this.apiBase}): ${msg} — ` +
          `keeping ${this.projects.length} stale project(s) in memory`,
      );
    }
  }

  /**
   * Fetch projects from the registry sidecar. Expected response shape:
   *   { success: true, settings: { projects: [...] } }
   */
  private async _fetchProjects(): Promise<RawRegistryProject[]> {
    const url = `${this.apiBase}/api/settings/global`;
    const res = await fetch(url, { signal: AbortSignal.timeout(5_000) });
    if (!res.ok) {
      throw new Error(`HTTP ${res.status} from ${url}`);
    }
    const body = (await res.json()) as {
      success?: boolean;
      settings?: { projects?: RawRegistryProject[] };
    };
    if (!body.success) {
      throw new Error(`registry returned success=false`);
    }
    return body.settings?.projects ?? [];
  }

  private _enrichProject(p: RawRegistryProject): RegistryProject {
    const enriched: RegistryProject = {
      id: p.id,
      name: p.name,
      slug: deriveSlug(p.name),
      path: p.path,
    };

    // Prefer the served native github/defaultBranch — it's the source of truth
    // and survives GitHub repo renames (deriving from the local clone's
    // .git/config drifts on rename, e.g. contentMachine → protoContent silently
    // broke routing until the remote was re-pointed). Fall back to .git
    // derivation only when the field is omitted.
    if (p.github?.owner && p.github?.repo) {
      enriched.github = { owner: p.github.owner, repo: p.github.repo };
    } else {
      const gitConfigPath = join(p.path, ".git", "config");
      if (existsSync(gitConfigPath)) {
        try {
          const github = parseGithubFromGitConfig(readFileSync(gitConfigPath, "utf8"));
          if (github) enriched.github = github;
        } catch {
          // Silent — non-essential enrichment.
        }
      }
    }

    if (p.defaultBranch) {
      enriched.defaultBranch = p.defaultBranch;
    } else {
      const headRefPath = join(p.path, ".git", "refs", "remotes", "origin", "HEAD");
      if (existsSync(headRefPath)) {
        try {
          const branch = parseDefaultBranchFromHead(readFileSync(headRefPath, "utf8").trim());
          if (branch) enriched.defaultBranch = branch;
        } catch {
          // Silent — non-essential enrichment.
        }
      }
    }

    return enriched;
  }
}

// ── Exported helpers (pure, testable) ────────────────────────────────────────

/**
 * Drop projects whose derived slug collides with an earlier one — `getBySlug`
 * must be deterministic, and a collision would make project-channel resolution
 * silently pick whichever entry happened to sort first. Keep the first
 * occurrence and warn loudly so the operator can rename one in the registry.
 */
export function dedupeBySlug(projects: RegistryProject[]): RegistryProject[] {
  const seen = new Set<string>();
  const out: RegistryProject[] = [];
  for (const p of projects) {
    if (seen.has(p.slug)) {
      log.warn(
        `duplicate slug "${p.slug}" — keeping the first project, ` +
          `dropping "${p.name}" (${p.path}). Rename one in the registry to disambiguate.`,
      );
      continue;
    }
    seen.add(p.slug);
    out.push(p);
  }
  return out;
}

/**
 * Derive a topic-safe slug from a project name. Matches the slug shape
 * the old `workspace/projects.yaml` used (lowercase repo name with dots
 * replaced by dashes — e.g. `rabbit-hole.io` → `rabbit-hole-io`).
 */
export function deriveSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

/**
 * Parse the `[remote "origin"]` url from a git config file and extract
 * owner/repo. Supports SSH (`git@github.com:OWNER/REPO.git`), HTTPS
 * (`https://github.com/OWNER/REPO.git`), and `.git` suffix optional.
 * Returns undefined if no GitHub origin remote is found.
 */
export function parseGithubFromGitConfig(
  config: string,
): { owner: string; repo: string } | undefined {
  const lines = config.split("\n");
  let inOriginSection = false;
  let originUrl: string | undefined;
  for (const line of lines) {
    const sectionMatch = line.match(/^\s*\[(.+)\]\s*$/);
    if (sectionMatch) {
      inOriginSection = /remote\s+"origin"/.test(sectionMatch[1]!);
      continue;
    }
    if (!inOriginSection) continue;
    const urlMatch = line.match(/^\s*url\s*=\s*(.+?)\s*$/);
    if (urlMatch) {
      originUrl = urlMatch[1]!;
      break;
    }
  }
  if (!originUrl) return undefined;

  const sshMatch = originUrl.match(/^git@github\.com:([^/]+)\/(.+?)(?:\.git)?$/);
  if (sshMatch) return { owner: sshMatch[1]!, repo: sshMatch[2]! };

  const httpsMatch = originUrl.match(/^https?:\/\/github\.com\/([^/]+)\/(.+?)(?:\.git)?$/);
  if (httpsMatch) return { owner: httpsMatch[1]!, repo: httpsMatch[2]! };

  return undefined;
}

/**
 * Parse `<path>/.git/refs/remotes/origin/HEAD` contents to extract the
 * default branch name. The file typically contains a symref like
 * `ref: refs/remotes/origin/main`.
 */
export function parseDefaultBranchFromHead(headContent: string): string | undefined {
  const match = headContent.trim().match(/^ref:\s*refs\/remotes\/origin\/(.+)$/);
  return match ? match[1]! : undefined;
}
